import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 24,
    paddingLeft: 20,
    backgroundColor: 'transparent',
    gap: 20,
    overflow: 'visible',
  },
  header: {
    gap: 4,
  },
  pageTitle: {
    ...typography.titleL,
    color: 'var(--color-text-primary)',
    lineHeight: 36,
  },
  pageSubtitle: {
    ...typography.body1,
    color: 'var(--color-text-muted)',
    lineHeight: 24,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'center',
  },
  filterPill: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  filterPillActive: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundColor: 'var(--color-vhu-primary)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-vhu-primary)',
    borderRightColor: 'var(--color-vhu-primary)',
    borderBottomColor: 'var(--color-vhu-primary)',
    borderLeftColor: 'var(--color-vhu-primary)',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(29, 65, 138, 0.25)',
  },
  filterPillText: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '500',
  },
  filterPillTextActive: {
    ...typography.subTitle2,
    color: 'var(--color-text-on-primary)',
    fontWeight: '600',
  },
  list: {
    overflow: 'visible',
  },
  listContent: {
    gap: 16,
    paddingBottom: 24,
    overflow: 'visible',
  },
  lessonItem: {
    width: '100%',
    maxWidth: '25%',
    minWidth: 0,
  },
  title: {
    ...typography.subTitle2,
  },

  // Empty State
  emptyContainer: {
    backgroundColor: 'var(--color-surface)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    paddingTop: 48,
    paddingRight: 24,
    paddingBottom: 48,
    paddingLeft: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginTop: 8,
    boxShadow: '0 4px 14px rgba(15, 23, 42, 0.04)',
  },
  emptyIconWrapper: {
    width: 64,
    height: 64,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundColor: 'var(--color-surface-subtle)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    ...typography.titleS,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyDesc: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    textAlign: 'center',
    maxWidth: 420,
    lineHeight: 20,
  },
  emptyActionBtn: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 10,
    paddingBottom: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: 'var(--color-vhu-primary)',
    cursor: 'pointer',
    marginTop: 8,
  },
  emptyActionText: {
    ...typography.buttonSmall,
    color: 'var(--color-text-on-primary)',
    fontWeight: '600',
  },
});

export default styles;
