import { lexend, inter, StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginLeft: 20,
    marginRight: 20,
  },
  containerMobile: {
    marginLeft: 12,
    marginRight: 12,
  },
  header: {
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 8,
    alignItems: 'flex-start',
  },
  title: {
    ...typography.titleM,
  },
  subTitle: {
    ...typography.body1,
    color: '#8D8D8D',
  },
  headerTitle: {
    fontWeight: '600',
    fontSize: 22.78,
  },
  chip: {
    ...typography.titleS,
  },
  categoryItem: {
    paddingTop: 7,
    paddingBottom: 7,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    backgroundColor: '#FFF',
  },
  categoryItemName: {
    ...typography.subTitle2,
    color: '#212121',
  },
  description: {
    ...typography.body1,
    color: '#8D8D8D',
    paddingBottom: 12,
  },
  whatLearnTitle: {
    ...typography.subTitle1,
    color: '#FFA726',
  },
  learnedSkillText: {
    ...typography.subTitle1,
    margin: 0,
  },
  moduleContentHeader: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  moduleTitleText: {
    ...typography.subTitle1,
    margin: 0,
    flex: 1,
    minWidth: 0,
  },
  moduleCountText: {
    ...typography.subTitle1,
    margin: 0,
    flexShrink: 0,
  },
  skillLearnedItem: {
    ...typography.body2,
    color: '#21212199',
  },
  lessonContent: {
    flex: 1,
  },
  lessonContentTitle: {
    ...typography.titleS,
  },
  button: {
    backgroundColor: 'var(--color-vhu-primary)',
    alignSelf: 'flex-start',
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  buttonText: {
    color: 'white',
  },
  buttonModule: {
    flexDirection: 'row',
    paddingLeft: 16,
    paddingRight: 16,
    flex: 1,
    borderRadius: 8,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: 'white',
    gap: 16,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)', // Shadow
  },
  moduleItemTitle: {
    fontFamily: lexend.style.fontFamily,
    fontWeight: '400',
    fontSize: 16,
    letterSpacing: 0.01,
    color: '#212121',
  },
  moduleItemTime: {
    ...typography.body2,
    color: '#8D8D8D',
  },
  layoutRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
  },
  videoSticky: {
    position: 'sticky' as any,
    top: 0,
    zIndex: 3,
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
  },
  sideColumn: {
    width: '40%',
    minWidth: 340,
    maxWidth: 440,
    gap: 16,
    alignSelf: 'flex-start',
    position: 'sticky' as any,
    top: 16,
  },
  faceWrapper: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 0,
    overflow: 'hidden',
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.08)',
  },
  lessonScroll: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingRight: 16,
    paddingLeft: 16,
    paddingBottom: 16,
    boxShadow: '0 8px 16px rgba(0, 0, 0, 0.08)',
    overflowY: 'auto',
  },
  lessonScrollContent: {
    flex: 1,
    height: '100%',
    paddingBottom: 16,
    gap: 12,
  },
  lessonContentHeader: {
    backgroundColor: '#fff',
    width: '100%',
    paddingRight: 16,
    paddingLeft: 16,
    paddingTop: 16,
  },
  layoutTitleContainer: {
    width: '100%',
    display: 'flex',
    gap: 8,
    flexDirection: 'column',
  },
  // Hàng chứa tiêu đề bài học + nút "Hỏi đáp" cạnh nhau - mô tả (nếu có)
  // đứng riêng bên dưới, full width, không bị kéo vào chung hàng này.
  titleRow: {
    width: '100%',
    display: 'flex',
    gap: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // Nhóm 2 nút bên phải titleRow (Đánh giá khóa học + Hỏi đáp) lại với nhau
  // để justify-content:space-between của titleRow chỉ tách title/nhóm nút,
  // không tách rời 2 nút ra xa nhau.
  titleRowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  noteBox: {
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    gap: 4,
  },
  noteBoxTitle: {
    ...typography.subTitle2,
    color: '#92400e',
    fontWeight: '600',
  },
  noteBoxText: {
    ...typography.body2,
    color: '#78350f',
    lineHeight: 20,
  },
  contentMetaText: {
    ...typography.body2,
    color: '#8D8D8D',
  },
  contentNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  contentNavButton: {
    flex: 1,
    minWidth: 0,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 8,
    backgroundColor: '#f5f5f7',
    cursor: 'pointer',
  },
  contentNavButtonDisabled: {
    flex: 1,
    minWidth: 0,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 8,
    backgroundColor: '#f5f5f7',
    opacity: 0.4,
  },
  contentNavButtonText: {
    ...typography.body2,
    color: '#212121',
    fontWeight: '500',
  },
  layoutTitle: {
    ...typography.titleM,
    fontSize: 28,
    marginTop: 16,
    marginBottom: 16,
  },
  layoutTitleMobile: {
    fontSize: 19,
    marginTop: 8,
    marginBottom: 8,
    lineHeight: '26px',
  },
  contentGap8Margin8: {
    gap: 8,
    marginTop: 8,
  },
  libraryItemPadding: {
    paddingRight: 7,
    paddingLeft: 7,
    flex: 1,
  },
  errorText: {
    color: 'red',
  },
  centeredFlex: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullWidthFlex: {
    width: '100%',
    flex: 1,
  },
  libraryGap: {
    gap: 12,
  },
  modalContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  resultCard: {
    border: '1px solid #f0f0f0',
    borderRadius: '8px',
    padding: '16px',
    marginBottom: '16px',
    backgroundColor: '#fafafa',
    width: '90%',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  statusBoxSuccess: {
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '16px',
    fontWeight: 500,
    backgroundColor: '#f6ffed',
    color: '#389e0d',
    width: '90%',
  },
  statusBoxFail: {
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '16px',
    fontWeight: 500,
    backgroundColor: '#fff1f0',
    color: '#cf1322',
    width: '90%',
  },
  scoreSuccess: {
    color: '#0958d9',
    fontWeight: 'bold',
  },
  scoreFail: {
    color: '#cf1322',
    fontWeight: 'bold',
  },
  aiFeedbackBox: {
    padding: '14px 16px',
    borderRadius: '8px',
    marginBottom: '16px',
    backgroundColor: '#f0f5ff',
    color: '#1d418a',
    fontSize: 14,
    lineHeight: '20px',
    width: '90%',
    textAlign: 'left' as const,
  },
});

export default styles;
