import { StyleSheet, typography } from '@styles';

const CARD = {
  backgroundColor: 'var(--color-surface)',
  borderTopWidth: 1,
  borderRightWidth: 1,
  borderBottomWidth: 1,
  borderLeftWidth: 1,
  borderTopStyle: 'solid',
  borderRightStyle: 'solid',
  borderBottomStyle: 'solid',
  borderLeftStyle: 'solid',
  borderTopColor: 'var(--color-border)',
  borderRightColor: 'var(--color-border)',
  borderBottomColor: 'var(--color-border)',
  borderLeftColor: 'var(--color-border)',
  borderTopLeftRadius: 14,
  borderTopRightRadius: 14,
  borderBottomRightRadius: 14,
  borderBottomLeftRadius: 14,
} as const;

const BUTTON_RESET = {
  display: 'flex',
  fontFamily: 'inherit',
  cursor: 'pointer',
  textAlign: 'left',
} as const;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingLeft: 20,
    paddingRight: 20,
  },
  containerMobile: {
    paddingLeft: 12,
    paddingRight: 12,
  },
  layoutRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
  },
  skeletonColumn: {
    gap: 24,
  },
  videoSticky: {
    position: 'sticky' as any,
    top: 0,
    zIndex: 3,
    width: '100%',
    backgroundColor: 'var(--color-surface)',
    borderRadius: 12,
  },
  layoutTitleContainer: {
    width: '100%',
    gap: 12,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
  },
  titleRow: {
    width: '100%',
    gap: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  titleRowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  layoutTitle: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    lineHeight: 30,
  },
  layoutTitleMobile: {
    ...typography.titleMMobile,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  description: {
    ...typography.body1,
    color: 'var(--color-text-body)',
    lineHeight: 28,
  },
  contentMetaText: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
  },
  fullWidthFlex: {
    width: '100%',
    flex: 1,
  },
  noteCallout: {
    backgroundColor: 'var(--color-info-bg)',
    borderRadius: 8,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
  },
  noteBoxText: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 21,
  },
  tabEmptyText: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    paddingTop: 4,
    paddingBottom: 4,
  },
  documentList: {
    gap: 8,
  },
  documentRow: {
    ...BUTTON_RESET,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    minHeight: 48,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface)',
  },
  documentIcon: {
    fontSize: 18,
    color: 'var(--color-vhu-primary)',
  },
  documentTitle: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    flex: 1,
    minWidth: 0,
  },
  documentKind: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    flexShrink: 0,
  },
  contentNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
  },
  navButton: {
    ...BUTTON_RESET,
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 16,
    paddingRight: 16,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-strong)',
    borderRightColor: 'var(--color-border-strong)',
    borderBottomColor: 'var(--color-border-strong)',
    borderLeftColor: 'var(--color-border-strong)',
    backgroundColor: 'var(--color-surface)',
  },
  navButtonForward: {
    justifyContent: 'flex-end',
    borderTopColor: 'var(--color-vhu-primary)',
    borderRightColor: 'var(--color-vhu-primary)',
    borderBottomColor: 'var(--color-vhu-primary)',
    borderLeftColor: 'var(--color-vhu-primary)',
    backgroundColor: 'var(--color-vhu-primary)',
  },
  navButtonDisabled: {
    cursor: 'not-allowed',
    opacity: 0.45,
  },
  navTextBack: {
    ...typography.buttonSmall,
    color: 'var(--color-text-primary)',
  },
  navTextForward: {
    ...typography.buttonSmall,
    color: 'var(--color-text-on-primary)',
  },
  backBar: {
    ...BUTTON_RESET,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    minHeight: 44,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  backBarIcon: {
    fontSize: 12,
    color: 'var(--color-vhu-primary)',
  },
  backBarText: {
    ...typography.buttonSmall,
    color: 'var(--color-vhu-primary)',
  },
  stateBox: {
    ...CARD,
    alignItems: 'center',
    gap: 12,
    paddingTop: 44,
    paddingBottom: 44,
    paddingLeft: 20,
    paddingRight: 20,
  },
  errorText: {
    ...typography.body2,
    color: 'var(--color-error)',
    textAlign: 'center',
  },
  emptyText: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    textAlign: 'center',
  },
});

export default styles;
