import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  card: {
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    boxShadow: '0 6px 18px rgba(17, 24, 39, 0.08)',
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  titleCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  robotIconWrapper: {
    width: 36,
    height: 36,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: 'var(--color-info-bg)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    ...typography.subTitle1,
    color: 'var(--color-vhu-primary)',
    fontWeight: '700',
    lineHeight: 24,
  },
  aiBadge: {
    backgroundColor: 'var(--color-vhu-secondary)',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
  },
  aiBadgeText: {
    ...typography.caption,
    color: 'var(--color-text-primary)',
    fontWeight: '700',
    lineHeight: 14,
  },
  summaryBox: {
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
  },
  summary: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 22,
  },
  suggestedList: {
    gap: 10,
  },
  suggestedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    paddingTop: 10,
    paddingRight: 12,
    paddingBottom: 10,
    paddingLeft: 12,
    cursor: 'pointer',
    gap: 12,
  },
  suggestedLeft: {
    flex: 1,
    gap: 4,
  },
  courseName: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    lineHeight: 18,
  },
  tagsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  levelTag: {
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 4,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
  },
  levelTagText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 14,
  },
  hotBadge: {
    backgroundColor: '#fee2e2', // red tint
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 4,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
  },
  hotBadgeText: {
    ...typography.caption,
    color: '#b91c1c',
    fontWeight: '700',
    lineHeight: 14,
  },
  durationText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 14,
  },
  footerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'var(--color-border-subtle)',
    borderTopStyle: 'solid',
    paddingTop: 12,
    cursor: 'pointer',
  },
  link: {
    ...typography.body2,
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
    lineHeight: 20,
  },
});

export default styles;
