import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    minWidth: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    backgroundColor: 'var(--color-surface)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    overflow: 'hidden',
    boxShadow: '0 4px 14px rgba(15, 23, 42, 0.05)',
  },
  content: {
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    justifyContent: 'space-between',
    gap: 8,
  },
  cardThumbnail: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    backgroundColor: 'var(--color-surface-subtle)',
    position: 'relative',
  },
  inner: {
    flex: 1,
  },
  premiumIcon: {
    color: 'var(--color-text-on-primary)',
    fontSize: 24,
  },
  inProgressBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    zIndex: 2,
    backgroundColor: 'var(--color-vhu-primary)',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 4,
    paddingBottom: 4,
  },
  inProgressBadgeText: {
    ...typography.caption,
    fontWeight: '600',
    color: 'var(--color-text-on-primary)',
    lineHeight: 16,
  },
  title: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    lineHeight: 22,
  },
  desc: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    lineHeight: 20,
  },
  price: {
    ...typography.titleS,
    color: 'var(--color-premium)',
  },
  statsRow: {
    flexDirection: 'row',
    marginTop: 6,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
  },
  statItem: {
    gap: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  statIcon: {
    fontSize: 16,
    color: 'var(--color-vhu-primary)',
  },
  ratingStarIcon: {
    color: 'var(--color-vhu-secondary)',
  },
  statValue: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    fontWeight: '500',
  },
  statLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  premium: {
    position: 'absolute',
    top: 8,
    zIndex: 2,
    left: 8,
    height: 32,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    ...typography.body2,
    backgroundColor: 'var(--color-premium)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
  },
  actionRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  enterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 6,
    paddingRight: 10,
    paddingBottom: 6,
    paddingLeft: 10,
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
  },
  enterBtnText: {
    ...typography.caption,
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
    lineHeight: 16,
  },
});

export default styles;
