import { StyleSheet } from '@styles';

export default StyleSheet.create({
  wrapper: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    zIndex: 9999,
  },
  panel: {
    width: 320,
    backgroundColor: 'white',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ccc',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    backgroundColor: '#ef405c',
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerText: {
    color: 'white',
    fontWeight: 'bold',
  },
  closeBtn: {
    color: 'white',
    fontSize: 16,
  },
  chatArea: {
    padding: 12,
    height: 300,
  },
  bubble: {
    padding: 8,
    borderRadius: 8,
    maxWidth: '90%',
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#dbeafe',
  },
  aiBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#f3f4f6',
  },
  line: {
    marginBottom: 4,
  },
  lessonBox: {
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 3,
    marginVertical: 8,
    gap: 12,
  },
  lessonInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  thumbnailWrapper: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#eee',
  },
  lessonTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111',
  },
  lessonPrice: {
    marginTop: 4,
    color: '#EF405C',
    fontWeight: '600',
  },
  lessonLink: {
    textAlign: 'center',
    backgroundColor: '#ef405c',
    color: 'white',
    paddingVertical: 8,
    borderRadius: 8,
    fontWeight: 'bold',
    fontSize: 14,
  },
  loadingText: {
    fontStyle: 'italic',
    color: '#888',
  },
  inputWrapper: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderColor: '#ccc',
    padding: 8,
  },
  input: {
    flex: 1,
    padding: 8,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#ccc',
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  sendBtn: {
    backgroundColor: '#ef405c',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    justifyContent: 'center',
  },
  sendText: {
    color: 'white',
  },
  fab: {
    backgroundColor: '#ef405c',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 9999,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  fabText: {
    color: 'white',
    fontSize: 14,
  },
});
