import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    paddingTop: 24,
    paddingRight: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    boxShadow: '0 6px 18px rgba(17, 24, 39, 0.08)',
    gap: 20,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  leftCol: {
    flex: 1,
    minWidth: 260,
    gap: 8,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  greetingText: {
    ...typography.titleM,
    color: 'var(--color-vhu-primary)',
    lineHeight: 30,
  },
  quoteText: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff7ed', // orange subtle tint
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: '#ffedd5',
    borderRightColor: '#ffedd5',
    borderBottomColor: '#ffedd5',
    borderLeftColor: '#ffedd5',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    paddingTop: 6,
    paddingRight: 14,
    paddingBottom: 6,
    paddingLeft: 12,
  },
  streakText: {
    ...typography.buttonSmall,
    color: '#ea580c',
    lineHeight: 20,
    fontWeight: '700',
  },
  streakSubText: {
    ...typography.caption,
    color: '#c2410c',
    lineHeight: 16,
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'var(--color-surface-selected)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    paddingTop: 6,
    paddingRight: 14,
    paddingBottom: 6,
    paddingLeft: 12,
  },
  levelText: {
    ...typography.buttonSmall,
    color: 'var(--color-vhu-primary)',
    lineHeight: 20,
    fontWeight: '700',
  },
  // Gamification & Level Track Section
  gamificationSection: {
    borderTopWidth: 1,
    borderTopColor: 'var(--color-border-subtle)',
    borderTopStyle: 'solid',
    paddingTop: 16,
    gap: 12,
  },
  gamificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  levelInfoCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  levelRankLabel: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    lineHeight: 20,
  },
  xpCountText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  progressBarWrapper: {
    width: '100%',
    height: 10,
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    overflow: 'hidden',
    position: 'relative',
  },
  progressBarFill: {
    height: '100%',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  dailyGoalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    paddingTop: 4,
  },
  dailyGoalText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    lineHeight: 18,
  },
  celebrateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'var(--color-success-bg)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-success)',
    borderRightColor: 'var(--color-success)',
    borderBottomColor: 'var(--color-success)',
    borderLeftColor: 'var(--color-success)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    paddingTop: 6,
    paddingRight: 12,
    paddingBottom: 6,
    paddingLeft: 12,
    cursor: 'pointer',
  },
  celebrateBtnDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
  },
  celebrateBtnText: {
    ...typography.caption,
    color: 'var(--color-success)',
    fontWeight: '600',
    lineHeight: 16,
  },
  celebrateBtnTextDisabled: {
    color: 'var(--color-text-muted)',
  },
});

export default styles;
