import { StyleSheet, typography, lexend } from '@styles';

const styles = StyleSheet.create({
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid #f0f0f0',
  },
  headerTitle: {
    fontFamily: lexend.style.fontFamily,
    fontWeight: '600',
    fontSize: 16,
    color: '#212121',
  },
  countTag: {
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
  },
  headerActions: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  card: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    borderRadius: 12,
    border: '1px solid #f0f0f0',
    backgroundColor: '#fff',
  },
  avatar: {
    width: 40,
    height: 40,
    fontSize: 15,
    flexShrink: 0,
  },
  cardBody: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  name: {
    ...typography.body1,
    fontWeight: '600',
    fontSize: 14,
    color: '#212121',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  meRow: {
    fontSize: 11,
    height: 20,
    lineHeight: '20px',
    margin: 0,
    borderRadius: 999,
  },
  doneTag: {
    fontSize: 11,
    height: 20,
    lineHeight: '20px',
    margin: 0,
    borderRadius: 999,
  },
  email: {
    ...typography.body2,
    fontSize: 12,
    color: '#8D8D8D',
    marginBottom: 6,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  progressRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  progressBarWrap: {
    flex: 1,
  },
  progressLabel: {
    fontSize: 12,
    color: '#8D8D8D',
    minWidth: 34,
    textAlign: 'right',
  },
  metaRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  metaText: {
    fontSize: 11,
    color: '#a3a3a3',
  },
  emptyWrap: {
    padding: '32px 0',
  },
  paginationRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 16,
    paddingTop: 12,
    borderTop: '1px solid #f0f0f0',
  },
  pageText: {
    fontSize: 12,
    color: '#595959',
    minWidth: 60,
    textAlign: 'center',
  },
});

export default styles;
