import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: 'var(--color-surface)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    paddingRight: 24,
    alignItems: 'center',
  },
  name: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    marginTop: 14,
    textAlign: 'center',
  },
  subtitle: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    marginTop: 4,
    textAlign: 'center',
  },
  changeAvatarBtn: {
    marginTop: 16,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 16,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomLeftRadius: 999,
    borderBottomRightRadius: 999,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: 'var(--color-border-strong)',
    borderBottomColor: 'var(--color-border-strong)',
    borderLeftColor: 'var(--color-border-strong)',
    borderRightColor: 'var(--color-border-strong)',
    cursor: 'pointer',
  },
  changeAvatarText: {
    ...typography.body2,
    fontWeight: '600',
    color: 'var(--color-text-primary)',
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: 'var(--color-border-subtle)',
    marginTop: 20,
    marginBottom: 16,
  },
  joinedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  joinedLabel: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
  },
  joinedValue: {
    ...typography.body2,
    fontWeight: '600',
    color: 'var(--color-text-primary)',
  },
});

export default styles;
