import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    paddingRight: 24,
    backgroundColor: 'var(--color-surface, #fff)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.04)',
  },
  headerWrapper: {
    marginBottom: 16,
  },
  pageTitle: {
    margin: 0,
    ...typography.titleL,
    color: 'var(--color-text-primary)',
  },
  title: {
    ...typography.body2,
    fontWeight: '500',
  },
  subTitle: {
    ...typography.body1,
  },
  // Thanh tab xuống dòng (không menu "..."): hàng cách 10, cột cách 24.
  tabStrip: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 10,
    columnGap: 24,
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  tab: {
    ...typography.body1,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    backgroundColor: 'transparent',
    color: 'var(--color-text-primary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
    transitionProperty: 'color, border-color',
    transitionDuration: '0.16s',
    transitionTimingFunction: 'ease',
  },
  tabActive: {
    color: 'var(--color-vhu-primary)',
    borderBottomColor: 'var(--color-vhu-primary)',
    fontWeight: '600',
  },
});

export default styles;
