import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '35%',
    alignSelf: 'center',
    padding: 20,
    margin: 20,
  },
  footer: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  labelText: {
    margin: 0,
    ...typography.button,
  },
  subContainer: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 24,
  },
  subTitle: {
    ...typography.titleM,
    color: '#000000',
  },
  subDescription: {
    ...typography.body2,
    color: '#21212199',
  },
  driverContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    gap: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  driver: { width: '100%', height: 1, opacity: 0.32, backgroundColor: 'black' },
  driverText: {
    ...typography.body1,
  },
  forgotWrapper: {
    alignItems: 'flex-end',
    marginBottom: 16,
  },
  forgotTitle: {
    color: 'var(--color-vhu-primary)',
    cursor: 'pointer',
  },
  containerDesktop: {
    flex: 4,
    width: '100%',
    alignSelf: 'center',
    padding: 20,
    margin: 70,
    maxWidth: 600,
  },
  containerTablet: {
    flex: 1,
    width: '100%',
    maxWidth: 540,
    alignSelf: 'center',
    padding: 16,
    margin: 16,
  },
  containerMobile: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    padding: 12,
    margin: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
    boxShadow: 'none',
  },
  layoutDesktop: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  layoutTablet: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    width: '100%',
    alignItems: 'center',
  },
  layoutMobile: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    width: '100%',
    alignItems: 'center',
  },
  heroDesktop: {
    flex: 6,
    minWidth: 340,
    height: '100vh',
    backgroundColor: 'var(--color-vhu-primary)',
    backgroundImage:
      'linear-gradient(150deg, var(--color-vhu-primary), #2a5bb8)',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroMobile: {
    width: '100%',
    backgroundColor: 'var(--color-vhu-primary)',
    backgroundImage:
      'linear-gradient(150deg, var(--color-vhu-primary), #2a5bb8)',
    borderRadius: 16,
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroLogo: {
    width: 56,
    height: 56,
    borderRadius: 14,
    backgroundColor: '#fff',
    objectFit: 'contain',
    padding: 6,
  },
  heroTitle: {
    ...typography.titleM,
    color: '#ffffff',
    fontSize: 26,
  },
  heroSlogan: {
    ...typography.body1,
    textAlign: 'center',
    color: '#e6ecfa',
    maxWidth: 340,
  },
  formWrapper: {
    flex: 1,
    minWidth: 320,
    display: 'flex',
    flexDirection: 'column',
  },
  primaryButton: {
    backgroundColor: 'var(--color-vhu-primary)',
    borderColor: 'var(--color-vhu-primary)',
    color: '#ffffff',
    borderRadius: 10,
    fontWeight: '600',
    boxShadow: '0 2px 8px rgba(29, 65, 138, 0.28)',
  },
  googleButton: {
    backgroundColor: '#ffffff',
    borderColor: '#e5e7eb',
    color: '#111827',
    borderRadius: 10,
    fontWeight: '500',
  },
  pageWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    position: 'relative',
  },
});

export default styles;
