import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    gap: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    ...typography.titleS,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    lineHeight: 28,
  },
  grid: {
    flexDirection: 'row',
    gap: 16,
    width: '100%',
    flexWrap: 'wrap',
  },
  // Bento Card Base
  card: {
    flex: 1,
    minWidth: 220,
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    boxShadow: '0 6px 18px rgba(17, 24, 39, 0.08)',
    justifyContent: 'space-between',
    gap: 12,
    position: 'relative',
    cursor: 'pointer',
  },
  // Card Highlight cho Thời gian học (rộng hơn)
  cardHighlight: {
    flex: 1.2,
    minWidth: 260,
    backgroundColor: 'var(--color-surface)',
    borderTopColor: 'var(--color-border-strong)',
    borderRightColor: 'var(--color-border-strong)',
    borderBottomColor: 'var(--color-border-strong)',
    borderLeftColor: 'var(--color-border-strong)',
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  iconWrapper: {
    width: 44,
    height: 44,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    backgroundColor: 'var(--color-surface-subtle)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrapperWarning: {
    width: 44,
    height: 44,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    backgroundColor: 'var(--color-warning-bg)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrapperSuccess: {
    width: 44,
    height: 44,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderBottomLeftRadius: 12,
    backgroundColor: 'var(--color-success-bg)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagBadge: {
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    borderBottomLeftRadius: 6,
    paddingTop: 4,
    paddingRight: 8,
    paddingBottom: 4,
    paddingLeft: 8,
  },
  tagBadgeSuccess: {
    backgroundColor: 'var(--color-success-bg)',
  },
  tagBadgeWarning: {
    backgroundColor: 'var(--color-warning-bg)',
  },
  tagBadgeTextSuccess: {
    ...typography.caption,
    color: 'var(--color-success)',
    fontWeight: '600',
    lineHeight: 14,
  },
  tagBadgeTextWarning: {
    ...typography.caption,
    color: 'var(--color-warning)',
    fontWeight: '600',
    lineHeight: 14,
  },
  cardContent: {
    gap: 4,
  },
  cardLabel: {
    ...typography.subTitle2,
    color: 'var(--color-text-muted)',
    lineHeight: 20,
  },
  cardValue: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    fontWeight: '700',
    lineHeight: 30,
  },
  cardCaption: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  cardFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: 'var(--color-border-subtle)',
    borderTopStyle: 'solid',
    paddingTop: 10,
    marginTop: 4,
  },
  cardActionLink: {
    ...typography.caption,
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
    lineHeight: 16,
  },
});

export default styles;
