import type { CSSProperties } from 'react';

// Style inline, không phụ thuộc theme/redux của dashboard: các trang này phải
// render được hoàn toàn phía server cho Google đọc, không kèm client provider.
const styles: Record<string, CSSProperties> = {
  page: {
    maxWidth: 960,
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
    paddingTop: 32,
    paddingRight: 20,
    paddingBottom: 64,
    paddingLeft: 20,
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    color: '#1f2430',
    lineHeight: 1.6,
  },
  breadcrumb: { fontSize: 14, color: '#6b7280', marginBottom: 16 },
  h1: { fontSize: 32, lineHeight: 1.25, margin: '0 0 12px' },
  lead: { fontSize: 16, color: '#4b5563', margin: '0 0 28px' },
  empty: { color: '#6b7280' },
  grid: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'grid',
    gap: 20,
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
  },
  card: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e2e8f0',
    borderRadius: 16,
    padding: 24,
    background: '#fff',
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.05)',
  },
  cardTitle: { fontSize: 20, fontWeight: 700, margin: '0 0 10px' },
  cardLink: { color: '#1d418a', textDecoration: 'none' },
  cardDesc: {
    fontSize: 14,
    color: '#4b5563',
    margin: '0 0 12px',
    lineHeight: 1.5,
  },
  meta: { fontSize: 13, color: '#6b7280', margin: '0 0 8px' },
  skills: { fontSize: 13, color: '#4b5563', margin: '0 0 14px' },
  cta: {
    display: 'inline-block',
    fontSize: 14,
    fontWeight: 600,
    color: '#1d418a',
    textDecoration: 'none',
  },
  // --- trang chi tiết ---
  hero: { margin: '0 0 24px' },
  section: { margin: '28px 0' },
  h2: { fontSize: 22, fontWeight: 700, margin: '0 0 12px' },
  list: { margin: 0, paddingLeft: 20, color: '#374151' },
  ctaBox: {
    marginTop: 32,
    padding: 24,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#dbeafe',
    background: '#f8faff',
    borderRadius: 16,
    boxShadow: '0 4px 16px rgba(29, 65, 138, 0.06)',
  },
  ctaBtn: {
    display: 'inline-block',
    marginTop: 12,
    paddingTop: 12,
    paddingRight: 24,
    paddingBottom: 12,
    paddingLeft: 24,
    background: '#1d418a',
    color: '#fff',
    borderRadius: 10,
    textDecoration: 'none',
    fontWeight: 600,
  },
};

export default styles;
