import { StyleSheet } from '@styles';

export default StyleSheet.create({
  wrapper: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    zIndex: 9999,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
  },
  fab: {
    backgroundColor: 'var(--color-vhu-primary)',
    borderRadius: 9999,
    boxShadow: '0 8px 20px rgba(29, 65, 138, 0.35)',
  },
  fabInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 18,
    paddingRight: 18,
    color: '#fff',
    fontSize: 18,
    cursor: 'pointer',
  },
  fabText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  panel: {
    width: 380,
    maxWidth: 'calc(100vw - 48px)',
    height: 520,
    maxHeight: 'calc(100vh - 120px)',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    boxShadow: '0 20px 60px rgba(0,0,0,0.25)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    background: 'linear-gradient(135deg, #1d418a 0%, #2c5aa8 100%)',
    padding: '16px 18px',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    flexShrink: 0,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 9999,
    backgroundColor: 'rgba(255,255,255,0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 18,
    flexShrink: 0,
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 14.5,
    fontWeight: 700,
    margin: 0,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
    margin: 0,
    marginTop: 2,
  },
  headerCloseBtn: {
    background: 'transparent',
    border: 'none',
    color: 'rgba(255,255,255,0.85)',
    cursor: 'pointer',
    fontSize: 16,
    padding: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    flexShrink: 0,
  },
  body: {
    flex: 1,
    overflowY: 'auto' as any,
    padding: '16px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    backgroundColor: '#f5f7fb',
  },
  bubbleRowAssistant: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    maxWidth: '100%',
  },
  bubbleRowUser: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  bubbleAvatar: {
    width: 28,
    height: 28,
    borderRadius: 9999,
    backgroundColor: '#1d418a',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    flexShrink: 0,
  },
  bubbleAssistant: {
    backgroundColor: '#ffffff',
    borderRadius: '4px 16px 16px 16px',
    padding: '12px 14px',
    fontSize: 13.5,
    lineHeight: '20px',
    color: '#1f2937',
    boxShadow: '0 2px 8px rgba(29,65,138,0.08)',
    maxWidth: 270,
  },
  bubbleUser: {
    backgroundColor: '#1d418a',
    color: '#fff',
    borderRadius: '16px 4px 16px 16px',
    padding: '10px 14px',
    fontSize: 13.5,
    lineHeight: '19px',
    maxWidth: 240,
  },
  typingDots: {
    display: 'flex',
    gap: 4,
    padding: '4px 2px',
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 9999,
    backgroundColor: '#9aa8c7',
  },
  roadmapList: {
    marginTop: 10,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  roadmapStep: {
    display: 'flex',
    gap: 10,
    alignItems: 'flex-start',
  },
  roadmapStepIndex: {
    width: 20,
    height: 20,
    borderRadius: 9999,
    backgroundColor: '#e6f0fa',
    color: '#1d418a',
    fontSize: 11,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 1,
  },
  roadmapStepText: {
    fontSize: 13,
    lineHeight: '19px',
    color: '#374151',
  },
  roadmapDeadline: {
    color: '#8fa3d6',
    fontSize: 12,
  },
  courseOverviewTotal: {
    marginTop: 4,
    paddingTop: 8,
    borderTop: '1px dashed #e5e7eb',
    fontSize: 12.5,
    fontWeight: 600,
    color: '#1d418a',
  },
  ctaButton: {
    marginTop: 12,
    width: '100%',
    height: 36,
    borderRadius: 10,
    backgroundColor: 'var(--color-vhu-primary)',
    border: 'none',
    color: '#fff',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  quickReplyRow: {
    marginTop: 10,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  quickReplyChip: {
    textAlign: 'left' as const,
    padding: '9px 12px',
    borderRadius: 10,
    border: '1px solid #dbe4f3',
    backgroundColor: '#f5f8fd',
    color: '#1d418a',
    fontSize: 12.5,
    fontWeight: 600,
    cursor: 'pointer',
  },
  footer: {
    padding: 12,
    borderTop: '1px solid #eef1f6',
    backgroundColor: '#fff',
    flexShrink: 0,
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  input: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    border: '1px solid #dbe4f3',
    backgroundColor: '#f5f7fb',
    padding: '0 16px',
    fontSize: 13,
    color: '#1f2937',
    outline: 'none',
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 9999,
    backgroundColor: 'var(--color-vhu-primary)',
    border: 'none',
    color: '#fff',
    fontSize: 15,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  askButtonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
});
