import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    gap: 20,
  },
  headerBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  headerTextGroup: {
    gap: 4,
    flex: 1,
    minWidth: 260,
  },
  pageTitle: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
  },
  subtitle: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
    maxWidth: 720,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
  },
  statCard: {
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 20,
    paddingRight: 20,
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.04)',
    gap: 6,
  },
  statLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statValue: {
    ...typography.titleL,
    color: 'var(--color-vhu-primary)',
    fontWeight: '700',
  },
  controlCard: {
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 20,
    paddingRight: 20,
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.04)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  controlLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    flex: 1,
    minWidth: 280,
  },
  searchInput: {
    width: 260,
    height: 40,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  createButton: {
    height: 40,
    paddingLeft: 20,
    paddingRight: 20,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    boxShadow: '0 2px 8px rgba(13, 71, 161, 0.2)',
  },
  createButtonText: {
    ...typography.button,
    color: 'var(--color-text-on-primary)',
  },
  tableCard: {
    flex: 1,
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    borderRightColor: 'var(--color-border)',
    borderBottomColor: 'var(--color-border)',
    borderLeftColor: 'var(--color-border)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    boxShadow: '0 4px 16px rgba(15, 23, 42, 0.04)',
    overflow: 'hidden',
  },
  examTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
  },
  cellText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
  },
  actionLinkEdit: {
    ...typography.buttonSmall,
    color: 'var(--color-vhu-primary)',
    cursor: 'pointer',
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 8,
    paddingRight: 8,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  actionLinkDelete: {
    ...typography.buttonSmall,
    color: 'var(--color-error)',
    cursor: 'pointer',
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 8,
    paddingRight: 8,
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
});

export default styles;
