import { StyleSheet } from '@styles';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    width: '100%',
    paddingTop: 8,
  },
  skeletonCard: {
    backgroundColor: 'var(--color-surface)',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    borderRightColor: 'var(--color-border-subtle)',
    borderBottomColor: 'var(--color-border-subtle)',
    borderLeftColor: 'var(--color-border-subtle)',
    overflow: 'hidden',
    boxShadow: '0 4px 14px rgba(15, 23, 42, 0.04)',
  },
  skeletonThumb: {
    width: '100%',
    aspectRatio: 16 / 9,
    backgroundColor: 'var(--color-surface-subtle)',
  },
  content: {
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    gap: 12,
  },
  lineTitle: {
    width: '85%',
    height: 18,
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    borderBottomLeftRadius: 6,
  },
  lineDesc: {
    width: '60%',
    height: 14,
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 4,
  },
  lineFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
  },
  lineBadge: {
    width: 60,
    height: 16,
    backgroundColor: 'var(--color-surface-subtle)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 4,
  },
});

export default styles;
