import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  banner: {
    width: '100%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    paddingTop: 24,
    paddingRight: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    backgroundColor: 'var(--color-vhu-primary)',
    backgroundImage:
      'linear-gradient(135deg, var(--color-vhu-primary) 0%, #15316b 60%, #0f2452 100%)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 24,
    flexWrap: 'wrap',
    boxShadow: '0 10px 26px rgba(17, 24, 39, 0.10)',
    position: 'relative',
    overflow: 'hidden',
  },
  bannerSkeleton: {
    width: '100%',
    height: 148,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    backgroundColor: 'var(--color-border-subtle)',
    backgroundImage:
      'linear-gradient(90deg, var(--color-border-subtle) 0%, var(--color-surface) 50%, var(--color-border-subtle) 100%)',
    backgroundSize: '600px 100%',
    backgroundRepeat: 'no-repeat',
    animationName: 'shimmer',
    animationDuration: '1.4s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  textCol: {
    gap: 8,
    flex: 1,
    minWidth: 240,
  },
  cardTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    alignSelf: 'flex-start',
  },
  cardTagText: {
    ...typography.caption,
    color: 'var(--color-vhu-secondary)',
    fontWeight: '600',
    lineHeight: 16,
  },
  greeting: {
    ...typography.body1,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 24,
  },
  headline: {
    ...typography.titleM,
    color: 'var(--color-text-on-primary)',
    lineHeight: 30,
    fontWeight: '600',
  },
  subtitle: {
    ...typography.body2,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 20,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  rightCol: {
    alignItems: 'flex-end',
    gap: 8,
    minWidth: 160,
  },
  progressPercent: {
    ...typography.displayL,
    color: 'var(--color-vhu-secondary)',
    lineHeight: 38,
  },
  progressTrack: {
    width: 160,
    height: 8,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    borderBottomLeftRadius: 999,
    backgroundImage:
      'linear-gradient(90deg, var(--color-vhu-accent) 0%, var(--color-vhu-secondary) 100%)',
    backgroundColor: 'var(--color-vhu-secondary)',
  },
  progressCaption: {
    ...typography.body2,
    color: 'rgba(255, 255, 255, 0.75)',
    lineHeight: 20,
  },
  ctaButton: {
    width: 'auto',
    backgroundColor: 'var(--color-vhu-secondary)',
    borderTopColor: 'var(--color-vhu-secondary)',
    borderRightColor: 'var(--color-vhu-secondary)',
    borderBottomColor: 'var(--color-vhu-secondary)',
    borderLeftColor: 'var(--color-vhu-secondary)',
    color: 'var(--color-text-primary)',
    fontWeight: '600',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  secondaryButton: {
    width: 'auto',
    backgroundColor: 'transparent',
    borderTopColor: 'rgba(255, 255, 255, 0.6)',
    borderRightColor: 'rgba(255, 255, 255, 0.6)',
    borderBottomColor: 'rgba(255, 255, 255, 0.6)',
    borderLeftColor: 'rgba(255, 255, 255, 0.6)',
    color: 'var(--color-text-on-primary)',
  },
});

export default styles;
