import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  pageLayout: {
    minHeight: '100vh',
    backgroundColor: 'var(--color-surface)',
    padding: 16,
    gap: 16,
  },
  header: {
    padding: 0,
    backgroundColor: 'transparent',
  },
  mainLayout: {
    backgroundColor: 'var(--color-surface)',
    gap: 16,
  },
  sider: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: 12,
    minHeight: 'calc(100vh - 80px)',
    backgroundColor: 'var(--color-surface)',
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border-subtle)',
  },
  logo: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingRight: 12,
    paddingLeft: 12,
    paddingTop: 10,
    paddingBottom: 10,
  },
  logoMark: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  logoMarkText: {
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
    fontSize: 16,
  },
  logoText: {
    color: 'var(--color-text-primary)',
    fontWeight: '700',
    fontSize: 16,
  },
  topbar: {
    paddingTop: 24,
    paddingBottom: 24,
    backgroundColor: 'var(--color-surface)',
    color: 'var(--color-text-primary)',
    position: 'sticky',
    top: 0,
    zIndex: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    minHeight: 64,
  },
  topbarRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    width: '100%',
  },
  searchWrap: {
    flex: 1,
    maxWidth: 540,
    alignSelf: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  searchInput: {
    backgroundColor: 'var(--color-surface-subtle)',
    borderRadius: 999,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    height: 40,
    paddingTop: 12,
    paddingBottom: 12,
  },
  actions: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    justifyContent: 'flex-end',
  },
  actionBtn: {
    color: 'var(--color-text-primary)',
    fontWeight: '600',
  },
  iconBtn: {
    color: 'var(--color-text-primary)',
    fontSize: 20,
  },
  avatar: {
    cursor: 'pointer',
    backgroundColor: 'var(--color-vhu-primary)',
    width: 40,
    height: 40,
  },
  menu: {
    backgroundColor: 'transparent',
    borderInlineEnd: 0,
  },
  content: {
    backgroundColor: 'var(--color-surface)',
    minHeight: 'calc(100vh - 80px)',
  },
  btnOpenDrawer: {
    color: 'var(--color-text-primary)',
    fontSize: 20,
  },
  antSider: {
    position: 'sticky',
    top: 64,
    alignSelf: 'flex-start',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'var(--color-surface)',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    transition: 'width 0.2s ease',
  },
  collapseToggleBtn: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 8,
    paddingRight: 8,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    cursor: 'pointer',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
  },
  collapseToggleText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    fontWeight: '500',
    lineHeight: 16,
  },
});

export default styles;
