import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  pageContainer: {
    width: '100%',
    minHeight: '100%',
    backgroundColor: 'var(--color-surface-page)',
    flexDirection: 'column',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 80,
    paddingBottom: 80,
  },
  // Sticky header top of ExamRoom
  header: {
    backgroundColor: 'var(--color-surface)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 16,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
    position: 'sticky',
    top: 0,
    zIndex: 5,
  },
  headerMobile: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    gap: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  backButton: {
    height: 40,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    flexShrink: 0,
  },
  backButtonText: {
    ...typography.subTitle2,
    color: 'var(--color-text-body)',
  },
  subjectIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  subjectIconBadgeText: {
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
    ...typography.subTitle1,
  },
  headerTitleCol: {
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  headerTitle: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    lineHeight: 28,
  },
  headerTitleMobile: {
    ...typography.titleMMobile,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  headerMeta: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  statusChip: {
    height: 32,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  statusChipText: {
    ...typography.subTitle2,
    fontWeight: '500',
    lineHeight: 20,
  },
  // Body: flex-wrap main + aside
  bodyRow: {
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 20,
    paddingBottom: 40,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
    alignItems: 'flex-start',
    width: '100%',
  },
  bodyRowMobile: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    paddingBottom: 80,
    flexDirection: 'column',
    gap: 16,
  },
  mainCol: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: 16,
  },
  asideCol: {
    width: 340,
    maxWidth: '100%',
    flexShrink: 0,
    flexDirection: 'column',
    gap: 16,
  },
  asideColMobile: {
    width: '100%',
  },
  // Tab Bar
  tabList: {
    flexDirection: 'row',
    gap: 4,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    overflowX: 'auto',
  },
  tabItem: {
    height: 44,
    paddingLeft: 14,
    paddingRight: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    marginBottom: -1,
    cursor: 'pointer',
    backgroundColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: 'var(--color-vhu-primary)',
  },
  tabItemText: {
    ...typography.subTitle2,
    color: 'var(--color-text-body)',
    lineHeight: 20,
  },
  tabItemTextActive: {
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
  },
  fixBadge: {
    minWidth: 20,
    height: 20,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 10,
    backgroundColor: 'var(--color-error-bg)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixBadgeText: {
    ...typography.caption,
    fontWeight: '600',
    color: 'var(--color-error)',
    lineHeight: 14,
  },
  // Card Yêu cầu đề bài
  card: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  cardHeader: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    flexDirection: 'column',
    gap: 6,
  },
  cardHeaderTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  cardHeaderTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  cardHeaderCounter: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  cardHeaderDesc: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  // Criterion list items
  criterionRow: {
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    backgroundColor: 'var(--color-surface)',
    flexDirection: 'column',
  },
  criterionRowExpanded: {
    backgroundColor: 'var(--color-surface-selected)',
  },
  criterionHeader: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  criterionNum: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  criterionNumText: {
    ...typography.caption,
    fontWeight: '600',
    lineHeight: 16,
  },
  criterionBody: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: 8,
  },
  criterionSummary: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 21,
  },
  criterionMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  typeBadge: {
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 4,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
  },
  typeBadgeText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    lineHeight: 16,
  },
  whereText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    lineHeight: 16,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    alignItems: 'center',
  },
  toggleBtn: {
    height: 32,
    paddingLeft: 8,
    paddingRight: 8,
    marginLeft: -8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 6,
  },
  toggleBtnText: {
    ...typography.subTitle2,
    color: 'var(--color-vhu-primary)',
    fontWeight: '500',
  },
  goFixBtn: {
    height: 32,
    paddingLeft: 8,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 6,
  },
  goFixBtnText: {
    ...typography.subTitle2,
    color: 'var(--color-error)',
    fontWeight: '500',
  },
  criterionStatusBadge: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 12,
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  criterionStatusBadgeText: {
    ...typography.caption,
    fontWeight: '500',
    lineHeight: 16,
  },
  // Preview panels
  previewWrap: {
    paddingLeft: 60,
    paddingRight: 20,
    paddingBottom: 16,
  },
  previewWrapMobile: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 14,
  },
  previewBox: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'var(--color-surface)',
    flexDirection: 'column',
  },
  // 4 states
  // 1) vReading
  readingContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    paddingBottom: 16,
    flexDirection: 'column',
    gap: 10,
  },
  readingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  readingHeaderText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
  },
  readingSkeletonGrid: {
    flexDirection: 'column',
    gap: 4,
  },
  readingSkeletonRow: {
    flexDirection: 'row',
    gap: 4,
  },
  readingSkeletonCell: {
    flex: 1,
    height: 24,
    backgroundColor: 'var(--color-border-subtle)',
    borderRadius: 2,
  },
  readingFooterNote: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  // 2) vError
  errorContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: 'var(--color-warning-bg)',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  errorIconBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'var(--color-warning)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  errorIconBadgeText: {
    ...typography.caption,
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
  },
  errorCol: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: 4,
  },
  errorTitle: {
    ...typography.subTitle2,
    fontWeight: '500',
    color: 'var(--color-text-primary)',
  },
  errorBody: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  // 3) vChart
  chartContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  chartIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'var(--color-info-bg)',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
    paddingBottom: 7,
    flexShrink: 0,
  },
  chartBar1: {
    width: 4,
    height: 8,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartBar2: {
    width: 4,
    height: 14,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartBar3: {
    width: 4,
    height: 11,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartCol: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: 4,
  },
  chartTitleText: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
  },
  chartNoteText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
  },
  // 4) vGrid
  gridTopBar: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: 'var(--color-surface-subtle)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  gridTopBarSheetText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
  },
  gridTopBarTargetText: {
    ...typography.caption,
    fontWeight: '500',
  },
  formulaBar: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    minWidth: 0,
    backgroundColor: 'var(--color-surface)',
  },
  formulaAddrBox: {
    width: 56,
    flexShrink: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    ...typography.caption,
    fontWeight: '500',
    color: 'var(--color-text-primary)',
    justifyContent: 'center',
  },
  formulaFxBox: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    ...typography.caption,
    fontStyle: 'italic',
    color: 'var(--color-text-muted)',
    justifyContent: 'center',
  },
  formulaValBox: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    fontFamily: 'ui-monospace, Consolas, monospace',
    ...typography.caption,
    color: 'var(--color-text-primary)',
    overflowX: 'auto',
    whiteSpace: 'nowrap',
    justifyContent: 'center',
  },
  tableScrollWrap: {
    width: '100%',
    overflowX: 'auto',
  },
  gridTable: {
    flexDirection: 'column',
    width: '100%',
    minWidth: 320,
  },
  gridRow: {
    flexDirection: 'row',
    width: '100%',
  },
  gridThCorner: {
    width: 36,
    height: 24,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  gridThCol: {
    minWidth: 72,
    flex: 1,
    height: 24,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridThColActive: {
    backgroundColor: 'var(--color-info-bg)',
  },
  gridThColText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    fontWeight: '500',
    lineHeight: 16,
  },
  gridThRow: {
    width: 36,
    height: 28,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  gridThRowActive: {
    backgroundColor: 'var(--color-info-bg)',
  },
  gridThRowFreeze: {
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-text-body)',
  },
  gridThRowText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    fontWeight: '500',
    lineHeight: 16,
  },
  gridTdCell: {
    minWidth: 72,
    flex: 1,
    height: 28,
    paddingLeft: 8,
    paddingRight: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface)',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  gridTdCellTargetPass: {
    backgroundColor: 'var(--color-success-bg)',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: 'var(--color-success)',
  },
  gridTdCellTargetFail: {
    backgroundColor: 'var(--color-error-bg)',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: 'var(--color-error)',
  },
  gridTdCellSelected: {
    backgroundColor: 'var(--color-surface-selected)',
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: 'var(--color-vhu-primary)',
  },
  gridTdCellText: {
    ...typography.caption,
    color: 'var(--color-text-primary)',
    lineHeight: 16,
  },
  gridFooterNote: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
  },
  // Tab 2: Hướng dẫn sửa lỗi
  fixContainer: {
    flexDirection: 'column',
    gap: 12,
  },
  fixIntroText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  fixCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    flexDirection: 'column',
    gap: 10,
  },
  fixCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
  },
  fixCardTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '500',
  },
  fixSummaryText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  fixStepList: {
    margin: 0,
    paddingLeft: 36,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: 'var(--color-surface-subtle)',
    borderRadius: 8,
    flexDirection: 'column',
    gap: 6,
  },
  fixStepText: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 21,
  },
  fixFooterNote: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
  },
  // Aside Column
  asideSection: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
    paddingBottom: 20,
    flexDirection: 'column',
    gap: 14,
  },
  scoreSection: {
    flexDirection: 'column',
    gap: 8,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  scoreLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  scoreBigText: {
    ...typography.displayL,
    fontWeight: '700',
    color: 'var(--color-vhu-primary)',
    lineHeight: 36,
  },
  scoreTotalText: {
    ...typography.body1,
    color: 'var(--color-text-muted)',
  },
  scoreNoteText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  uploadHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  uploadTitleCol: {
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  uploadTitleText: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '500',
  },
  uploadHintText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  uploadBtnCol: {
    flexDirection: 'column',
    gap: 8,
    width: '100%',
  },
  statusNoteBox: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  statusNoteText: {
    ...typography.body2,
    lineHeight: 20,
    flex: 1,
  },
  historyCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  historyHeader: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '500',
  },
  historyRow: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  historyAttemptLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    width: 44,
  },
  historyScoreText: {
    ...typography.subTitle2,
    fontWeight: '500',
    color: 'var(--color-text-primary)',
    flex: 1,
  },
  historyTimeText: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  bottomBarSticky: {
    position: 'sticky',
    bottom: 0,
    zIndex: 6,
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    gap: 8,
    boxShadow: '0 -4px 12px rgba(17,24,39,0.06)',
  },
  discussionBox: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: 20,
    flexDirection: 'column',
  },
  discussionTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    marginBottom: 16,
  },
  resultItemRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  resultItemTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
  },
  resultItemInstruction: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
    marginTop: 4,
  },
});

export default styles;
