import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 64,
    paddingBottom: 64,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    lineHeight: 28,
  },
  titleMobile: {
    ...typography.titleMMobile,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  tabList: {
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    overflowX: 'auto',
  },
  tabButton: {
    height: 44,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    cursor: 'pointer',
    marginBottom: -1,
  },
  tabButtonActive: {
    borderBottomColor: 'var(--color-vhu-primary)',
  },
  tabText: {
    ...typography.subTitle2,
    color: 'var(--color-text-body)',
    lineHeight: 20,
  },
  tabTextActive: {
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
  },
  badgeCount: {
    minWidth: 20,
    height: 20,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 10,
    backgroundColor: 'var(--color-error-bg)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeCountText: {
    ...typography.caption,
    fontWeight: '600',
    color: 'var(--color-error)',
    lineHeight: 14,
  },
  // Main layout: 2 columns on desktop, stacked on mobile
  mainLayout: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
    width: '100%',
  },
  mainLayoutMobile: {
    flexDirection: 'column',
    gap: 16,
  },
  mainColumn: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  sideColumn: {
    width: 320,
    maxWidth: '100%',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  sideColumnMobile: {
    width: '100%',
  },
  card: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  cardHeader: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  cardHeaderTop: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  cardTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  cardCounter: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  cardDesc: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  criteriaItem: {
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  criteriaItemRow: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 14,
    paddingBottom: 14,
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  criteriaNum: {
    width: 28,
    height: 28,
    borderRadius: 14,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  criteriaNumText: {
    ...typography.caption,
    fontWeight: '600',
    lineHeight: 16,
  },
  criteriaBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  criteriaText: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 21,
  },
  criteriaMetaRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  typeTag: {
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 4,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
  },
  typeTagText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    lineHeight: 16,
  },
  whereText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
    lineHeight: 16,
  },
  criteriaActionsRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    alignItems: 'center',
  },
  actionTextButton: {
    height: 32,
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 0,
    borderRadius: 6,
    backgroundColor: 'transparent',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
  },
  actionTextButtonBlue: {
    color: 'var(--color-vhu-primary)',
  },
  actionTextButtonRed: {
    color: 'var(--color-error)',
  },
  statusChip: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 2,
    paddingBottom: 2,
    borderRadius: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
    whiteSpace: 'nowrap',
  },
  statusChipText: {
    ...typography.caption,
    fontWeight: '500',
    lineHeight: 16,
  },
  previewWrapper: {
    paddingLeft: 60,
    paddingRight: 20,
    paddingBottom: 16,
  },
  previewWrapperMobile: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 14,
  },
  previewBox: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'var(--color-surface)',
  },
  // 4 preview states
  readingContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    paddingBottom: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  readingStatusRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  readingStatusText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
  },
  readingSkeletonGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  readingSkeletonRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
  },
  readingSkeletonCell: {
    flex: 1,
    height: 24,
    backgroundColor: 'var(--color-border-subtle)',
    borderRadius: 2,
  },
  readingNote: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  errorContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: 'var(--color-warning-bg)',
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  errorIconBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'var(--color-warning)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  errorIconText: {
    ...typography.caption,
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
  },
  errorTextCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
    flex: 1,
  },
  errorTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
  },
  errorBody: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  chartContainer: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  chartIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'var(--color-info-bg)',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
    paddingBottom: 7,
    flexShrink: 0,
  },
  chartBar1: {
    width: 4,
    height: 8,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartBar2: {
    width: 4,
    height: 14,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartBar3: {
    width: 4,
    height: 11,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  chartTextCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
    flex: 1,
  },
  chartTitle: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
  },
  chartNote: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
  },
  gridTopBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: 'var(--color-surface-subtle)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
  },
  gridTopBarLeft: {
    ...typography.caption,
    color: 'var(--color-text-body)',
  },
  gridTopBarRight: {
    ...typography.caption,
    fontWeight: '500',
  },
  formulaBar: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'stretch',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
    minWidth: 0,
    backgroundColor: 'var(--color-surface)',
  },
  formulaCellAddr: {
    width: 60,
    flexShrink: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    ...typography.caption,
    fontWeight: '500',
    color: 'var(--color-text-primary)',
    display: 'flex',
    alignItems: 'center',
  },
  formulaFxLabel: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: 'var(--color-border)',
    ...typography.caption,
    fontStyle: 'italic',
    color: 'var(--color-text-muted)',
    display: 'flex',
    alignItems: 'center',
  },
  formulaInputDisplay: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 8,
    paddingBottom: 8,
    ...typography.formulaMono,
    color: 'var(--color-text-primary)',
    overflowX: 'auto',
    whiteSpace: 'nowrap',
  },
  tableScrollContainer: {
    overflowX: 'auto',
    width: '100%',
  },
  gridTable: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  gridThCorner: {
    width: 36,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
  },
  gridThCol: {
    minWidth: 72,
    height: 26,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    ...typography.caption,
    color: 'var(--color-text-body)',
    fontWeight: '500',
    textAlign: 'center',
  },
  gridThColSelected: {
    backgroundColor: 'var(--color-info-bg)',
  },
  gridThRow: {
    width: 36,
    height: 28,
    backgroundColor: 'var(--color-surface-subtle)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    ...typography.caption,
    color: 'var(--color-text-body)',
    fontWeight: '500',
    textAlign: 'center',
  },
  gridThRowSelected: {
    backgroundColor: 'var(--color-info-bg)',
  },
  gridCell: {
    paddingLeft: 8,
    paddingRight: 8,
    height: 28,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    ...typography.caption,
    color: 'var(--color-text-primary)',
    whiteSpace: 'nowrap',
    cursor: 'cell',
  },
  gridFooter: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 8,
    paddingBottom: 8,
    ...typography.caption,
    color: 'var(--color-text-muted)',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    lineHeight: 18,
  },
  // Tab 2: Hướng dẫn sửa lỗi
  fixContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  fixIntro: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  fixArticle: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  fixArticleHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
    flexWrap: 'wrap',
  },
  fixTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
  },
  fixSummary: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  fixStepList: {
    margin: 0,
    paddingLeft: 36,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: 'var(--color-surface-subtle)',
    borderRadius: 8,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  fixStepItem: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    lineHeight: 21,
  },
  fixNoteFooter: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
  },
  // Aside Column: Card upload & score
  asideCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
    paddingBottom: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  scoreSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  scoreLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  scoreRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
    flexWrap: 'wrap',
  },
  scoreBig: {
    ...typography.displayL,
    fontWeight: '700',
    color: 'var(--color-vhu-primary)',
    lineHeight: 36,
  },
  scoreTotal: {
    ...typography.body1,
    color: 'var(--color-text-muted)',
    lineHeight: 24,
  },
  scoreNote: {
    ...typography.body2,
    color: 'var(--color-text-body)',
    lineHeight: 21,
  },
  uploadSubjectRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  subjectIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  subjectIconText: {
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
    ...typography.body1,
  },
  uploadTitleCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
  },
  uploadTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
  },
  uploadHint: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  uploadBtnCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    width: '100%',
  },
  statusNoteBox: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 8,
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
  },
  statusNoteText: {
    ...typography.body2,
    lineHeight: 20,
    flex: 1,
  },
  historyCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  historyHeader: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
  },
  historyRow: {
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 12,
    paddingBottom: 12,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  historyTime: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  historyScore: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    lineHeight: 20,
    flex: 1,
  },
  bottomBarSticky: {
    position: 'sticky',
    bottom: 0,
    zIndex: 6,
    backgroundColor: 'var(--color-surface)',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border)',
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
  },
  discussionSection: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: 20,
  },
  discussionTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
    marginBottom: 16,
  },
  // Result item row for export
  resultItemRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  resultItemTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
  },
  resultItemInstruction: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 18,
    marginTop: 4,
  },
});

export default styles;
