import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  page: {
    width: '100%',
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 20,
    paddingBottom: 48,
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    boxSizing: 'border-box',
  },
  pageMobile: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 16,
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 80,
    paddingBottom: 80,
  },
  header: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  headerMobile: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 14,
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  backButton: {
    height: 40,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    cursor: 'pointer',
    flexShrink: 0,
  },
  backButtonText: {
    ...typography.subTitle2,
    color: 'var(--color-text-body)',
  },
  subjectIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  subjectIconText: {
    color: 'var(--color-text-on-primary)',
    fontWeight: '700',
    ...typography.body1,
  },
  titleCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  title: {
    ...typography.titleM,
    color: 'var(--color-text-primary)',
    lineHeight: 28,
  },
  titleMobile: {
    ...typography.titleMMobile,
    color: 'var(--color-text-primary)',
    lineHeight: 24,
  },
  subtitle: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
    lineHeight: 16,
  },
  headerRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  headerRightMobile: {
    justifyContent: 'space-between',
    width: '100%',
  },
  progressBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 104,
  },
  progressText: {
    ...typography.caption,
    color: 'var(--color-text-body)',
  },
  progressBarTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: 'var(--color-border)',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: 'var(--color-vhu-primary)',
  },
  timerBox: {
    height: 40,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface-subtle)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timerBoxWarning: {
    borderColor: 'var(--color-warning)',
    backgroundColor: 'var(--color-warning-bg)',
  },
  timerTime: {
    ...typography.subTitle1,
    fontWeight: '600',
    color: 'var(--color-text-primary)',
    fontVariantNumeric: 'tabular-nums',
  },
  timerTimeWarning: {
    color: 'var(--color-warning)',
  },
  timerLabel: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  body: {
    display: 'flex',
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-start',
    width: '100%',
  },
  bodyMobile: {
    flexDirection: 'column',
    gap: 16,
  },
  sidebar: {
    width: 280,
    flexShrink: 0,
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    overflow: 'hidden',
    position: 'sticky',
    top: 88,
  },
  sidebarHeader: {
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: 'var(--color-surface-subtle)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  sidebarTitle: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
    fontWeight: '600',
  },
  sidebarCount: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  taskList: {
    display: 'flex',
    flexDirection: 'column',
  },
  taskItem: {
    width: '100%',
    paddingLeft: 14,
    paddingRight: 14,
    paddingTop: 12,
    paddingBottom: 12,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    backgroundColor: 'var(--color-surface)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    textAlign: 'left',
  },
  taskItemActive: {
    backgroundColor: 'var(--color-surface-selected)',
    borderLeftWidth: 3,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--color-vhu-primary)',
  },
  taskNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'var(--color-surface-subtle)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    ...typography.caption,
    fontWeight: '600',
    color: 'var(--color-text-body)',
  },
  taskNumberActive: {
    backgroundColor: 'var(--color-vhu-primary)',
    color: 'var(--color-text-on-primary)',
  },
  taskTitle: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
    flex: 1,
    minWidth: 0,
    lineHeight: 20,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  },
  chipsScrollRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    overflowX: 'auto',
    paddingBottom: 4,
    width: '100%',
  },
  chipItem: {
    minWidth: 56,
    height: 48,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    backgroundColor: 'var(--color-surface)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    cursor: 'pointer',
    flexShrink: 0,
  },
  chipItemActive: {
    borderWidth: 2,
    borderColor: 'var(--color-vhu-primary)',
    backgroundColor: 'var(--color-surface-selected)',
  },
  chipNumber: {
    ...typography.subTitle2,
    fontWeight: '600',
    color: 'var(--color-text-primary)',
  },
  contentArea: {
    flex: 1,
    minWidth: 0,
  },
  // Result view
  resultContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    width: '100%',
  },
  resultHeaderCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 20,
    paddingBottom: 20,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap',
  },
  resultHeaderLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  resultScoreBadge: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  resultScoreNum: {
    ...typography.displayL,
    fontWeight: '700',
    color: 'var(--color-vhu-primary)',
    lineHeight: 36,
  },
  resultScoreTotal: {
    ...typography.body1,
    color: 'var(--color-text-muted)',
  },
  resultTaskCard: {
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 16,
    paddingBottom: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  resultTaskHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
  },
  resultTaskTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
  },
  resultTaskScore: {
    ...typography.subTitle2,
    color: 'var(--color-text-body)',
  },
  resultCriteriaList: {
    display: 'flex',
    flexDirection: 'column',
  },
  discussionBox: {
    marginTop: 16,
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  discussionTitle: {
    ...typography.subTitle1,
    color: 'var(--color-text-primary)',
    marginBottom: 16,
  },
});

export default styles;
