import { StyleSheet, typography } from '@styles';

const styles = StyleSheet.create({
  shell: {
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: 'var(--color-surface)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 28,
    paddingRight: 28,
    backgroundColor: 'var(--color-vhu-primary)',
  },
  headerText: {
    gap: 4,
    minWidth: 0,
    flex: 1,
  },
  title: {
    ...typography.titleS,
    color: 'var(--color-text-on-primary)',
  },
  subline: {
    ...typography.body2,
    color: 'var(--color-text-on-primary-muted)',
  },
  closeButton: {
    ...typography.buttonSmall,
    height: 36,
    minWidth: 36,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-text-on-primary-muted)',
    backgroundColor: 'transparent',
    color: 'var(--color-text-on-primary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  inlineWrap: {
    gap: 24,
  },
  inlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  backButton: {
    ...typography.titleS,
    width: 44,
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-strong)',
    backgroundColor: 'var(--color-surface)',
    color: 'var(--color-text-primary)',
    cursor: 'pointer',
    fontFamily: 'inherit',
    flexShrink: 0,
  },
  inlineTitle: {
    ...typography.titleM,
    lineHeight: 30,
    color: 'var(--color-text-primary)',
  },
  inlineCode: {
    ...typography.body2,
    color: 'var(--color-text-muted)',
  },
  inlineSubline: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  inlineBody: {
    gap: 24,
  },
  body: {
    paddingTop: 24,
    paddingLeft: 28,
    paddingRight: 28,
    paddingBottom: 28,
    gap: 24,
  },
  tabStrip: {
    flexDirection: 'row',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
  },
  tab: {
    ...typography.subTitle2,
    height: 44,
    paddingLeft: 16,
    paddingRight: 16,
    marginBottom: -1,
    borderWidth: 0,
    borderBottomWidth: 2,
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    backgroundColor: 'transparent',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  tabActive: {
    borderBottomColor: 'var(--color-vhu-primary)',
    color: 'var(--color-vhu-primary)',
    fontWeight: '600',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoText: {
    ...typography.body2,
    color: 'var(--color-text-body)',
  },
  infoStrong: {
    ...typography.subTitle2,
    color: 'var(--color-text-primary)',
  },
  learnerCell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  learnerName: {
    ...typography.body2,
    color: 'var(--color-text-primary)',
  },
  caption: {
    ...typography.caption,
    color: 'var(--color-text-muted)',
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 12,
  },
  centerState: {
    alignItems: 'center',
    gap: 12,
    paddingTop: 44,
    paddingBottom: 44,
    paddingLeft: 20,
    paddingRight: 20,
  },
  skeletonWrap: {
    gap: 16,
    padding: 16,
    backgroundColor: 'var(--color-surface)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 12,
  },
  errorState: {
    backgroundColor: 'var(--color-error-bg)',
    borderRadius: 12,
  },
  emptyText: {
    ...typography.body2,
    color: 'var(--color-text-disabled)',
    textAlign: 'center',
  },
  errorText: {
    ...typography.body2,
    color: 'var(--color-error)',
    textAlign: 'center',
  },
});

export default styles;
